version: "3.7"

services:
  main:
    image: docuvault-main
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      FILE_PROXY_ADDR: "http://fileproxy:8080"
      CONVERT_ADDR: "http://convert:7000"
      ACCESS_JWT_SECRET: "twentyonepilots"
      REFRESH_JWT_SECRET: "radiohead"
      PUBLISH_JWT_SECRET: "haskell"
    depends_on:
      - postgres
      - redis

  convert:
    image: docuvault-convert 
    expose:
      - 7000
    environment:
      SERVER_ADDR: "convert"
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      FILE_PROXY_ADDR: "http://fileproxy:8080"
    depends_on:
      - postgres
      - redis

  # for grpc server, socket address must not be "localhost". It should be the ip address assigned from docker bridge network
  fileproxy:
    image: file-reverse-proxy
    expose:
      - 8080
    environment:
      SERVER_ADDR: "fileproxy"
      FILE_SERVER_NUM: 5
      FILE_SERVER_1_ADDR: "http://file1:9000"
      FILE_SERVER_2_ADDR: "http://file2:9000"
      FILE_SERVER_3_ADDR: "http://file3:9000"
      FILE_SERVER_4_ADDR: "http://file4:9000"
      FILE_SERVER_5_ADDR: "http://file5:9000"
    depends_on:
      - postgres
      - redis

  file1:
    image: docuvault-file
    volumes:
      - file1-data:/usr/local/bin/files
    expose:
      - 9000
    environment:
      SERVER_ADDR: "file1"
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      LOCAL_INSTANCE_NUM: 1
    depends_on:
      - postgres
      - redis
  file2:
    image: docuvault-file
    volumes:
      - file2-data:/usr/local/bin/files
    expose:
      - 9000
    environment:
      SERVER_ADDR: "file2"
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      LOCAL_INSTANCE_NUM: 1
    depends_on:
      - postgres
      - redis
  file3:
    image: docuvault-file
    volumes:
      - file3-data:/usr/local/bin/files
    expose:
      - 9000
    environment:
      SERVER_ADDR: "file3"
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      LOCAL_INSTANCE_NUM: 1
    depends_on:
      - postgres
      - redis
  file4:
    image: docuvault-file
    volumes:
      - file4-data:/usr/local/bin/files
    expose:
      - 9000
    environment:
      SERVER_ADDR: "file4"
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      LOCAL_INSTANCE_NUM: 1
    depends_on:
      - postgres
      - redis
  file5:
    image: docuvault-file
    volumes:
      - file5-data:/usr/local/bin/files
    expose:
      - 9000
    environment:
      SERVER_ADDR: "file5"
      DATABASE_URL: "postgres://docker:0347@postgres/docuvault"
      REDIS_URL: "redis://redis"
      LOCAL_INSTANCE_NUM: 1
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    volumes:
      - docuvault-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: "0347"
      POSTGRES_USER: "docker"
      POSTGRES_DB: "docuvault"
    ports:
      - 5431:5432

  redis:
    image: redis:latest
    ports:
      - 6378:6379

volumes:
  docuvault-data:
  file1-data:
  file2-data:
  file3-data:
  file4-data:
  file5-data:
