//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "docorg_scope")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub docorg_id: i32,
    pub scope_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::docorg::Entity",
        from = "Column::DocorgId",
        to = "super::docorg::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Docorg,
    #[sea_orm(
        belongs_to = "super::scope::Entity",
        from = "Column::ScopeId",
        to = "super::scope::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Scope,
}

impl Related<super::docorg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Docorg.def()
    }
}

impl Related<super::scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
