//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "docorg")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub prev_id: Option<i32>,
    pub docuser_id: i32,
    pub raw: String,
    pub title: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::docuser::Entity",
        from = "Column::DocuserId",
        to = "super::docuser::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Docuser,
}

impl Related<super::docuser::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Docuser.def()
    }
}

impl Related<super::scope::Entity> for Entity {
    fn to() -> RelationDef {
        super::docorg_scope::Relation::Scope.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::docorg_scope::Relation::Docorg.def().rev())
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::docorg_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::docorg_tag::Relation::Docorg.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
