//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "convert")]
pub struct Model {
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub docorg_id: i32,
    pub data: Option<String>,
    #[sea_orm(column_name = "CType", primary_key, auto_increment = false)]
    pub c_type: i32,
    #[sea_orm(column_name = "Status")]
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::docorg::Entity",
        from = "Column::DocorgId",
        to = "super::docorg::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Docorg,
}

impl Related<super::docorg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Docorg.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
